### ISSUE TITLE
Not really an issue as such, but... (Applied Energistics)

### ISSUE THREAD

**Issue by Hawk-v3** [aeroc/TradeBoothMod#1]
Hey, there, I enjoy your mod greatly, and having got AE, attempted to use it for an "automatic" shop. Now, while buildcraft pipes work fine for accessing your block, when I own it, AE doesn't seem to be able to. Is this an intentional thing, and could it be fixed one way or the other?

**Comment by Hawk-v3** [comment]
(22:27:55) Hawk_v3: AlgorithmX2: So, playing around with this mod some more and your own, the AE network can draw from this tradebooth, but not put stuff in it. Are they different access modes, or have I screwed something up somehere? The storage thing is bidirectional.
(22:28:15) AlgorithmX2: thats interesting..
(22:28:59) AlgorithmX2:         @Override        public boolean isItemValidForSlot(int i, ItemStack itemstack) {                // TODO Auto-generated method stub                return false;        }
(22:29:02) AlgorithmX2: thats the issue
(22:29:06) Hawk_v3: ?
(22:29:08) AlgorithmX2: https://github.com/aeroc/TradeBoothMod/blob/master/tradebooth/tileentity/TileEntityTradeBoothStorage.java#L284
(22:29:27) AlgorithmX2: prevents AE from inserting by saying everything is invalid
(22:30:22) AlgorithmX2: return true isntead of false
(22:30:37) Hawk_v3: Oh, well.
(22:30:41) Hawk_v3: thanks
(22:30:42) AlgorithmX2: or just tell him the issue and hope hill release a new build ;)

So, that's the problem from the AE dev. Sorry for bugging you!

**Comment by aeroc** [comment]
Which version of Trade Booth are you using? Do you only want this applied to the storage block, and not the "top" block?

**Comment by Hawk-v3** [comment]
Latest download in your topic for 1.6.4, and yes, as it's the storage that items need to be filled into and out of. As AE's storage bus block used for interfacing has a filter on it already, I'm not worried about getting something different in it.

**Comment by aeroc** [comment]
Alright, I'll try to update in the next 24 hours. =)

**Comment by Hawk-v3** [comment]
Thank you so much!

**Comment by aeroc** [comment]
Here's an updated version with just that one line changed to True.

http://www.gamogora.com/mods/tradebooth.0.6.4.2t.zip

I haven't released it as a public version yet, I'd like you to let me know if it works as intended, then I will share the link. Also, I was thinking about making it something you'd have to change in the config file, it would be false by default, so everyone who wanted to use that would have to change the setting to true. So please let me know if that change causes any trouble.

**Comment by Hawk-v3** [comment]
I'll check it out and keep you updated.

**Comment by Hawk-v3** [comment]
It works as intended! I haven't had a problem with it. :3
